#!/usr/bin/env bash

## Script To Manage Brightness using brightnessctl .

# Get brightness
get_backlight() {
  LIGHT=$(brightnessctl -m | awk -F, '{print $4}' | tr -d '%')
  echo "${LIGHT}%"
}

# Increase brightness
inc_backlight() {
  brightnessctl set +5%
}

# Decrease brightness
dec_backlight() {
  brightnessctl set 5%-
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
  get_backlight
elif [[ "$1" == "--inc" ]]; then
  inc_backlight
elif [[ "$1" == "--dec" ]]; then
  dec_backlight
else
  get_backlight
fi
