#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/hypr"
RASI="$DIR/rofi/launcher.rasi"

# Check if rofi is already running
if pgrep -x "rofi" >/dev/null; then
  pkill rofi
else
  # Launch rofi
  rofi -show drun -theme ${RASI}
fi
