#!/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Xauthority
${SCRIPTSDIR}/xauthority &
# Swayidle
swayidle -w \
	timeout 300 'hyprctl dispatch dpms off' \
	resume 'hyprctl dispatch dpms on' \
	timeout 460 "swaylock --clock -f --indicator --effect-blur 7x5 " \
	before-sleep "systemctl suspend" &
