#!/bin/bash

CONFIG="$HOME/.config/hypr/waybar/config.jsonc"
STYLE="$HOME/.config/hypr/waybar/style.css"

killall -9 waybar
waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
