#!/bin/bash

WALLPAPER_DIR="$HOME/.dotfiles/.config/hypr/bg/"
CURRENT_WALL=$(hyprctl hyprpaper listloaded | awk -F': ' '{print $2}')
MONITOR=$(hyprctl monitors | grep 'Monitor' | awk '{print $2}')

# Get a random wallpaper that is not the current one
WALLPAPER=$(find "$WALLPAPER_DIR" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)

# Apply the wallpaper
hyprctl hyprpaper unload all
hyprctl hyprpaper preload "$WALLPAPER"
hyprctl hyprpaper wallpaper "$MONITOR,$WALLPAPER"
