#!/bin/bash

WALLPAPERS_DIR="$HOME/.config/hypr/bg"

if [ -d "$WALLPAPERS_DIR" ]; then
  random_background=$(find "$WALLPAPERS_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' -o -iname '*.jpeg' \) | shuf -n 1)

  hyprctl hyprpaper unload all
  hyprctl hyprpaper preload "$random_background"
  hyprctl hyprpaper wallpaper ", $random_background"

fi
