exec-once = hypridle
exec-once=~/.config/hypr/scripts/startup
exec = $scriptsDir/wallpaper
exec-once = wl-paste --watch cliphist store
exec-once=systemctl --user start plasma-polkit-agent
exec-once=hyprctl setcursor Bibata-Modern-Ice 24
exec-once = ags
exec = xremap ~/.config/xremap/config.yml
exec = hyprswitch init --show-title --size-factor 5.5 --workspaces-per-row 5 &


