exec-once = hypridle
exec-once = hyprpaper
exec-once = ~/.config/hypr/scripts/startup
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --watch cliphist store
exec-once = hyprsunset -t 5500
exec = hyprpanel -q; hyprpanel
exec = ~/.config/hypr/scripts/wallpaper
exec-once = hyprswitch init --show-title &


