$mainMod = SUPER
$localBin = $HOME/.local/bin
$scriptsDir = $HOME/.config/hypr/scripts
$hyprDir = $HOME/.config/hypr
$term = kitty
$menu = $scriptsDir/wofi_menu
$fullmenu = $scriptsDir/fullmenu
$volume = $scriptsDir/volume
$brightness = $scriptsDir/brightness
$screenshot = $scriptsDir/screenshot
$lock = $scriptsDir/lockscreen
$colorpicker = $scriptsDir/colorpicker
$wofi_beats = $scriptsDir/wofi-beats
$files = nemo
$browser = zen-browser
$editor = nvim
$discord = discord
$ebook = foliate
$notifycmd = notify-send -h string:x-canonical-private-synchronous:hypr-cfg -u low

$alacritty   = ~/.config/hypr/scripts/alacritty
$foot        = ~/.config/hypr/scripts/foot
$volume      = ~/.config/hypr/scripts/volume
$backlight   = ~/.config/hypr/scripts/brightness
$lockscreen  = ~/.config/hypr/scripts/lockscreen
$wlogout     = ~/.config/hypr/scripts/wlogout

$rofi_launcher    = ~/.config/hypr/scripts/rofi_launcher
$rofi_runner      = ~/.config/hypr/scripts/rofi_runner
$rofi_music       = ~/.config/hypr/scripts/rofi_music
$rofi_network     = ~/.config/hypr/scripts/rofi_network
$rofi_bluetooth   = ~/.config/hypr/scripts/rofi_bluetooth
$rofi_powermenu   = ~/.config/hypr/scripts/rofi_powermenu
$rofi_screenshot  = ~/.config/hypr/scripts/rofi_screenshot
$rofi_asroot      = ~/.config/hypr/scripts/rofi_asroot

$wofi_menu        = ~/.config/hypr/scripts/wofi_menu
$wofi_powermenu   = ~/.config/hypr/scripts/wofi_powermenu
