if true then
  return {}
end
return {
  { "rcarriga/nvim-notify" },
  { "stevearc/dressing.nvim" },
  { "akinsho/bufferline.nvim" },
  { "nvim-lualine/lualine.nvim" },
  { "lukas-reineke/indent-blankline.nvim" },
  { "echasnovski/mini.indentscope" },
  { "folke/which-key.nvim" },
  { "folke/noice.nvim" },
  { "nvim-tree/nvim-web-devicons" },
  { "MunifTanjim/nui.nvim" },
  { "goolord/alpha-nvim" },
  { "nvimdev/dashboard-nvim" },
  { "dstein64/vim-startuptime" },
  { "folke/persistence.nvim" },
  { "nvim-lua/plenary.nvim" },
  { "mfussenegger/nvim-lint" },
  { "nvim-treesitter/nvim-treesitter" },
  { "nvim-neo-tree/neo-tree.nvim" },
  { "nvim-pack/nvim-spectre" },
  { "nvim-telescope/telescope.nvim" },
  { "folke/flash.nvim" },
  { "folke/trouble.nvim" },
  { "folke/todo-comments.nvim" },
  { "lewis6991/gitsigns.nvim" },
  { "RRethy/vim-illuminate" },
  { "echasnovski/mini.bufremove" },
  { "neovim/nvim-lspconfig" },
  { "kabouzeid/nvim-lspinstall" },
  { "hrsh7th/nvim-cmp" },
  { "L3MON4D3/LuaSnip" },
  { "rafamadriz/friendly-snippets" },
  { "saadparwaiz1/cmp_luasnip" },
  { "echasnovski/mini.pairs" },
  { "echasnovski/mini.surround" },
  { "JoosepAlviste/nvim-ts-context-commentstring" },
  { "echasnovski/mini.comment" },
  { "echasnovski/mini.ai" },
}
